# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b64ba4c1ac64a9b1c8e7add0d6a40754dde8c840e196817a2a01d3d20c8ac3d8623968b2c20b4e5d6981b30bbb133ff02dc3ae2c59e8831d7dd21b02d23dd1e

test:
  secret_key_base: 6a95b9674ccccb5b3ad08e07c7e68c36b78de2ff24380f5819a35209a579dbaf655d813a3ac7ceb620a7f704993b7605b657aac87f1fa72a4e4eb2ff222f4790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
